### ISSUE TITLE
Question of composing models

### ISSUE THREAD

**Issue by zugexiaodui** [tianyu139/tangent-model-composition#1]
According to the code:
https://github.com/tianyu139/tangent-model-composition/blob/be38b3d337387ff113125d0d201653839d1d6fc2/utils.py#L235-L254
It seems that he weights of different models are averaged.
However, according to Eq.(2) and the description "fixing the pre-trained model at w results in only a convex optimization in the remaining parameters," in the paper, how do you optimize the remaining parameters (i.e. \theta_i in Eq.(2) or \lambda_i in Eq.(3))?
Thanks!

**Comment by tianyu139** [comment]
Hi @zugexiaodui , thanks for reaching out.

The questions regarding averaging of model weights and optimizing \theta_i are two separate issues. Note that each component model corresponds to a single set of weights \theta_i, the optimization details of which are described in Appendix A of the paper.

The composition operation occurs after a collection of component models, equivalently {\theta_i}s, are obtained. To achieve this, we linearly combine {\theta_i} by weighting each component model uniformly (corresponding to \lambda_i = 1/|F| in Eq. (3)). This is equivalent to the averaging of all model weights {(w, \theta_i)}, including the initial set of weights, w, which are held constant across all models hence remains unchanged after composition. This naive yet effective choice of \lambda_i is also described in Appendix A. We do note that there might indeed exist smarter ways of choosing \lambda_i to obtain better results.

Let me know if this resolves your concerns.

**Comment by zugexiaodui** [comment]
Thank you for your timely reply. It solves my concern.
